# Generated by Django 6.0.3 on 2026-04-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_department_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="current_working_company",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="profile",
            name="working_domain",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
