# Generated by Django 6.0.3 on 2026-04-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_profile_current_working_company_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
