# Generated by Django 6.0.3 on 2026-04-09 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="marketplaceitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("electronics", "Electronics"),
                    ("books", "Books & Notes"),
                    ("furniture", "Furniture"),
                    ("clothing", "Clothing"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="marketplaceitem",
            name="location",
            field=models.CharField(
                blank=True, help_text="e.g., Hostel Block A, Room 102", max_length=150
            ),
        ),
        migrations.AlterField(
            model_name="marketplaceitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Available"),
                    ("reserved", "Reserved"),
                    ("sold", "Sold"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="OrderRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Optional message to seller"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buy_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_requests",
                        to="marketplace.marketplaceitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("item", "buyer")},
            },
        ),
    ]
