# Generated by Django 6.0.3 on 2026-04-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "— Select department —"),
                    ("AI_DS", "AI & DS"),
                    ("CS", "CS"),
                    ("IT", "IT"),
                    ("ENTC", "EN & TC"),
                    ("MECH", "Mechanical"),
                    ("ELEC", "Electrical"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
