# Generated by Django 6.0.3 on 2026-04-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamification", "0002_alter_useractivity_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useractivity",
            name="action",
            field=models.CharField(
                choices=[
                    ("post", "Created a post"),
                    ("comment", "Commented"),
                    ("like", "Liked a post"),
                    ("connect", "Made a connection"),
                    ("job_apply", "Applied for a job"),
                    ("upload", "Uploaded resource"),
                    ("project", "Joined a project"),
                    ("login", "Daily login"),
                    ("streak_update", "Updated streak"),
                    ("lost_found_solve", "Resolved lost & found"),
                    ("res_download", "10 Resource Downloads"),
                ],
                max_length=30,
            ),
        ),
    ]
