# Generated by Django 6.0.3 on 2026-04-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lost_found", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lostfounditem",
            name="deposited_at",
            field=models.CharField(
                blank=True,
                help_text="For found items, where is it currently kept?",
                max_length=200,
            ),
        ),
    ]
