# Generated by Django 6.0.3 on 2026-03-24 10:44

import apps.users.models
import django.contrib.auth.validators
import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        max_length=254,
                        unique=True,
                        verbose_name="email address",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("alumni", "Alumni"),
                            ("senior", "Senior"),
                            ("admin", "Admin"),
                        ],
                        db_index=True,
                        default="student",
                        max_length=16,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
            managers=[
                ("objects", apps.users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="ActivityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("mentorship_request", "Sent mentorship request"),
                            ("project_created", "Created a project"),
                            ("project_joined", "Joined a project"),
                            ("resource_upload", "Uploaded a resource"),
                            ("opportunity_apply", "Applied to opportunity"),
                            ("listing_posted", "Posted a marketplace listing"),
                            ("lost_found_report", "Filed a lost/found report"),
                            ("login", "Logged in"),
                        ],
                        max_length=32,
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=120)),
                ("event_date", models.DateField(db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "activity event",
                "verbose_name_plural": "activity events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ActivityStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("mentorship_requests_sent", models.PositiveIntegerField(default=0)),
                (
                    "mentorship_requests_received",
                    models.PositiveIntegerField(default=0),
                ),
                ("mentorships_completed", models.PositiveIntegerField(default=0)),
                ("projects_created", models.PositiveIntegerField(default=0)),
                ("projects_joined", models.PositiveIntegerField(default=0)),
                ("resources_uploaded", models.PositiveIntegerField(default=0)),
                ("resources_downloads", models.PositiveIntegerField(default=0)),
                ("opportunities_posted", models.PositiveIntegerField(default=0)),
                ("opportunities_applied", models.PositiveIntegerField(default=0)),
                ("listings_posted", models.PositiveIntegerField(default=0)),
                ("items_sold", models.PositiveIntegerField(default=0)),
                ("lost_found_reports", models.PositiveIntegerField(default=0)),
                ("last_active_at", models.DateTimeField(blank=True, null=True)),
                ("login_count", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "activity stats",
                "verbose_name_plural": "activity stats",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bio", models.TextField(blank=True, max_length=500)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="Profile picture. Stored in S3 via django-storages.",
                        null=True,
                        upload_to="avatars/%Y/%m/",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("IT", "Information Technology"),
                            ("CS", "Computer Science"),
                            ("AIDS", "AI & Data Science"),
                            ("ENTC", "Electronics & Telecom"),
                            ("MECH", "Mechanical"),
                            ("CIVIL", "Civil"),
                            ("OTHER", "Other"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FE", "First Year"),
                            ("SE", "Second Year"),
                            ("TE", "Third Year"),
                            ("BE", "Fourth Year"),
                            ("ALUMNI", "Alumni / Graduated"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "skills",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        help_text="E.g. ['Python', 'React', 'Machine Learning']",
                    ),
                ),
                ("github_link", models.URLField(blank=True)),
                ("linkedin_link", models.URLField(blank=True)),
                ("website_link", models.URLField(blank=True)),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="When False, profile is only visible to the owner and admins.",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "profile",
                "verbose_name_plural": "profiles",
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["role", "is_active"], name="users_user_role_e1ec1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activityevent",
            index=models.Index(
                fields=["user", "event_date"], name="users_activ_user_id_118621_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activityevent",
            index=models.Index(
                fields=["user", "event_type"], name="users_activ_user_id_f64f40_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["skills"], name="profile_skills_gin"),
        ),
    ]
