# Generated by Django 6.0.3 on 2026-04-02 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Scholarship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("provider", models.CharField(max_length=200)),
                (
                    "amount",
                    models.CharField(
                        blank=True,
                        help_text="e.g. ₹50,000 or Full tuition",
                        max_length=100,
                    ),
                ),
                (
                    "scholarship_type",
                    models.CharField(
                        choices=[
                            ("merit", "Merit-based"),
                            ("need", "Need-based"),
                            ("sport", "Sports"),
                            ("research", "Research"),
                            ("other", "Other"),
                        ],
                        default="merit",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("eligibility", models.TextField(blank=True)),
                ("apply_link", models.URLField(blank=True)),
                ("deadline", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "posted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posted_scholarships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
